title: MS Blog.
subtitle: Developer MS.
description: 안녕하세요. 이민승입니다.
url: 'https://minseung-lee.github.io'
baseurl: ''
urls:
  - text: About Me
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
#  - text: Shop
#    url: /shop
  - text: Contact Me
    url: /contact
#  - text: Styleguide
#    url: /styleguide
#  - text: Get Started
#    url: /get-started
author_logo: profile.png
author: Minseung Lee
author_bio: 'MS, start!! :D'
author_email: leems1029@nate.com
author_location: Republic Of Korea.
author_website_url: 'http://minseung-lee.github.io'
typewrite-text: >-
  안녕하세요. 개발자 이민승입니다.
author_work_experiences:
  - company_name: Ktoto
    company_logo: null
    company_url: 'http://www.ktoto.co.kr/'
    designation: Software Developer
    description: 국민체육진흥투표권 인터넷발매시스템 유지보수
    visibility: true
  - company_name: openit inc.
    company_logo: null
    company_url: 'https://www.openit.co.kr/welcome'
    designation: Software Developer
    description: SK 계열사 SI 프로젝트 개발 업무
    visibility: true
author_education_details:
  - college_logo: null
    college_name: MIT
    college_url: 'https://mit.org'
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: true
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: true
#twitter_username: minseung-lee
github_username: minseung-lee
#facebook_username: minseung-lee
linkedin_username: minseung-lee
#behance_username: minseung-lee
#instagram_username: minseung-lee
#medium_username: minseung-lee
#telegram_username: minseung-lee
#dribbble_username: minseung-lee
#flickr_username: minseung-lee
hyvor_talk_website_id: 476
#wakatime_username: sujaykundu777
mailchimp_form_url: null
formspree_email: leems1029@nate.com
markdown: kramdown
highlighter: rouge
permalink: pretty
google_analytics: UA-169614937-1
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts
  files_to_exclude: []
  nodes_to_index: article
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  - products
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
